"""empty message

Revision ID: 21aa8d3e5bc1
Revises: 
Create Date: 2022-03-16 09:30:05.559731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21aa8d3e5bc1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transport_type', sa.String(length=128), nullable=False),
    sa.Column('rent_fee', sa.String(length=128), nullable=False),
    sa.Column('location', sa.String(length=128), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transports')
    # ### end Alembic commands ###
